ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "I'm not a big fan of the government.$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "Rumor has that Mettenfuk has a\n"
    .string "water bender living around.\p"
    .string "They flooded a whole city!\n"
    .string "can you believe that?$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "Stupid Libs of Mettenfuk.\n"
    .string "These bitches made the centers\p"
    .string "free to use, I cant believe it!\n"
    .string "THEY'RE RUINING METTENFUK!$"

