Route3_Text_TunnelFromCeruleanTiring::
    .string "Whew… I better take a rest…\n"
    .string "Groan…\p"
    .string "That tunnel from CERULEAN takes a\n"
    .string "lot out of you!$"

Route3_Text_ColtonIntro::
    .string "Lets battle fatty!\n"
    .string "Adopted fatty!$"

Route3_Text_ColtonDefeat::
    .string "Fatty fatty no-parents!$"

Route3_Text_ColtonPostBattle::
    .string "Why I aughta!\n"
    .string "I will PRAY on your downfall!$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "I like jorts!\p"
    .string "They're delightfully comfy and\n"
    .string "easy to wear!$"

Route3_Text_BenDefeat::
    .string "Drats!$"

Route3_Text_BenPostBattle::
    .string "You better watch out for that\n"
    .string "Jort storm.\p"
    .string "I'd be shitting bricks if I\n"
    .string "were you.$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?$"

Route3_Text_JaniceDefeat::
    .string "You...\n$"
    .string "Idiot... and savage.$"

Route3_Text_JanicePostBattle::
    .string "Have...\n"
    .string "I peaked?$"

Route3_Text_GregIntro::
    .string "Are you a TRAINER?\n"
    .string "Let's get with it right away!$"

Route3_Text_GregDefeat::
    .string "If I had new POKéMON, I would've\n"
    .string "won!$"

Route3_Text_GregPostBattle::
    .string "If a POKéMON BOX on the PC gets\n"
    .string "full, just switch to another BOX.$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"

Route3_Text_SallyDefeat::
    .string "Be nice!$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by not\n"
    .string "letting TRAINERS see you.$"

Route3_Text_CalvinIntro::
    .string "Hey! You're not wearing shorts!\n"
    .string "What's wrong with you?$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "I always wear shorts, even in\n"
    .string "winter. That's my policy.$"

Route3_Text_JamesIntro::
    .string "I'll battle you with the POKéMON\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Trained POKéMON are stronger than\n"
    .string "the wild ones.$"

Route3_Text_RobinIntro::
    .string "EYEEEEE!\n"
    .string "I'm easily frightened?$"

Route3_Text_RobinDefeat::
    .string "That wasn't TOO bad.$"

Route3_Text_RobinPostBattle::
    .string "I just woke up here\n"
    .string "randomally.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "MT. MOON AHEAD$"

