ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "I have a test today.\n"
    .string "I'm actually freaking cooked!$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Be sure to read what's on the\n"
    .string "blackboard carefully!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "Red balls cap Potemon\n"
    .string "cannot leave after caught.\p"
    .string "person can only hold 6 pokeballs.\n"
    .string "cant capt other trainer pokemon.\p"
    .string "got a potemon, you are trainer\n"
    .string "treat you er pokemon wiht respect.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Second page…\p"
    .string "healthy pokemon cant catch\n"
    .string "very hard, beat it up first!\p"
    .string "give it pokeaids or other diseases.\n"
    .string "sleep is best for catching.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Third page…\p"
    .string "trainers want to battle other\n"
    .string "trainers to show dominance or smth.\p"
    .string "winning feels good!\n"
    .string "visit gyms to get badges\p"
    .string "badges are good :D$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "get 8 badges for league\p"
    .string "beat up elite four and then\n"
    .string "kick the champs ass!\p"
    .string "............\n"
    .string "............\p"
    .string "The rest of the notes are just\n"
    .string "drawings and scribbles.$"

ViridianCity_School_Text_TurnThePage::
    .string "These notes are a mess!\n"
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "GIRL: Hey!\n"
    .string "Don't look at my notes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "The blackboard lists POKéMON\n"
    .string "STATUS problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep::
    .string "A POKéMON can't attack if it's\n"
    .string "asleep.\p"
    .string "POKéMON will stay asleep even\n"
    .string "after battles.\p"
    .string "Use AWAKENING to awaken one\n"
    .string "from sleep.$"

ViridianCity_School_Text_ExplainBurn::
    .string "A burn reduces ATTACK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"

ViridianCity_School_Text_ExplainPoison::
    .string "When poisoned, a POKéMON's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an ANTIDOTE to cure poison!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "A frozen POKéMON becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering POKéMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Paralysis reduces SPEED and may\n"
    .string "prevent the POKéMON from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use PARLYZ HEAL for treatment.$"

