Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in FURSTOFIELD CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "I'm trying to find a cool Pokémon.\p"
    .string "No luck though, only stupid ass\n"
    .string "rats, birds and bugs.\p"
    .string "This just flat out\n"
    .string "ink pink stinks man.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PURGATORY - FURSTOFIELD CITY$"

