ViridianCity_Text_CanCarryMonsAnywhere::
    .string "This city once was the home\n"
    .string "of the Simpletons!\p"
    .string "But after they're 50th season,\n"
    .string "they moved to those damn\p"
    .string "big shot cities.\n"
    .string "But I've heard rumors that for\p"
    .string "season 73, they're going back to\n"
    .string "basics, hopefully that means\p"
    .string "Clromer May is homophobic again!$"

ViridianCity_Text_StupidTree::
    .string "Who is the asshole that put a\n"
    .string "tree infront of my freakin house!$"

ViridianCity_Text_GrandmaReal::
    .string "I never allow my little man to\n"
    .string "have an iPad when he's with me!\p"
    .string "I cant let him grow up to be\n"
    .string "terminally online, as the kids say!$"

ViridianCity_Text_HyperKid::
    .string "I'm so excited to watch my favorite\n"
    .string "streamer Key Senile!$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Hello there younging!\n"
    .string "I'm just tending the garden\p"
    .string "of this school!\p"
    .string ".........\n"
    .string ".........\p"
    .string "I remember the days when we used\n"
    .string "to have a gym here...\p"
    .string "We were able to get more\n"
    .string "tourists that way.\p"
    .string "The economy has been screwey since.$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "News has our old gym leader\n"
    .string "is visiting the old place!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "I very much dislike Caterpie.\n"
    .string "Do you HATE Caterpie?$"

ViridianCity_Text_OhOkayThen::
    .string "Ew, BEGONE FROM ME!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "YEEEEAAAAAH!\n"
    .string "CATERPIE FUCKIN SUCKS!\p"
    .string "HASTAG WEEDLESWEEP\n"
    .string "HASTAG WEEDLESWEEP.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "I don't get all the complaining!\n"
    .string "This city is pretty good,\p"
    .string "all things considered!\n"
    .string "People just like to complain.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "Sometimes I take my car and\n"
    .string "drive around town like an asshole.\p"
    .string "I think I hit like three\n"
    .string "kids yesterday.\p"
    .string "TOTALLY WORTH IT THOUGH\n"
    .string "shit was hilarious!$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "I SLIPPED MY DISK!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "POKéDEX.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a POKéMON,\n"
    .string "the POKéDEX automatically updates\l"
    .string "its data.\p"
    .string "…You don't know how to catch\n"
    .string "a POKéMON?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?\p"
    .string "And here, take this, too.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "POKéDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "POKéMON before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAINER TIPS\p"
    .string "Catch POKéMON and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAINER TIPS\p"
    .string "The battle moves of POKéMON are\n"
    .string "limited by their POWER POINTS, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "POKéMON at a POKéMON CENTER.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN GYM's doors are locked…$"

