ViridianCity_House_Text_NicknamingIsFun::
    .string "Coming up with nicknames is fun,\n"
    .string "but it take a lot of power in somebody\p"
    .string "to not name your 'Mon something vulgur.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "My daddy FRIGGIN loves POKéMON!$"

ViridianCity_House_Text_Speary::
    .string "StupidLib: Brib!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Name: StupidLib$"

